steps:
- name: 'docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/github.com/twopeas/sharpstatusapp:current', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/github.com/twopeas/sharpstatusapp:current']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'sharpstatus-webapp', '--image', 'gcr.io/PROJECT_ID/github.com/twopeas/sharpstatusapp:current', '--region', 'us-central1', '--platform', 'managed']

images: ['gcr.io/$PROJECT_ID/github.com/twopeas/sharpstatusapp:current']